---
- name: Central Manager
  hosts: central_manager
  become: true
  vars:
    hostname: "{{ inventory_hostname }}"
  vars_files:
    - secret_group_vars/all.yml
    - secret_group_vars/htcondor.yml
  collections:
    - devsec.hardening
  pre_tasks:
    - name: Install Dependencies
      package:
        name: rsync
      become: true
    - name: Set default version of Python
      alternatives:
        name: python
        path: /usr/bin/python3
        link: /usr/bin/python
    - name: Disable SELinux
      selinux:
        state: disabled
    - name: Enable epel-release for python3-virtualenv
      yum:
        name: epel-release
        state: present
    - name: Install python3-wheel-wheel (needed by python3-virtualenv)
      yum:
        name: python3-wheel-wheel
        enablerepo: devel
        state: present
    - name: Install python3-virtualenv
      yum:
        name: python3-virtualenv
        enablerepo: epel-release
        state: present
    - name: Install Dependencies
      package:
        name: [ 'python3-psycopg2', 'python3', 'pip']
      become: true
    # docker
    - name: Install docker pip package
      pip:
        name: docker
    - name: Set docker_users (Docker role)
      set_fact:
        docker_users: "rocky"
  post_tasks:
    - name: Condor auto approve
      ansible.builtin.cron:
        name: condor_auto_approve
        minute: 0
        job: "/usr/bin/condor_token_request_auto_approve -netblock 192.168.0.0/24 -lifetime 3600" # change for your range
  roles:
    - role: usegalaxy_eu.handy.os_setup 
      vars:
        enable_hostname: true
        enable_powertools: true        # geerlingguy.repo-epel role doesn't enable PowerTools repository
        enable_install_software: true  # Some extra admin tools (*top, vim, etc)
        enable_remap_user: true        # remap 999:999 user
    - usegalaxy-eu.dynmotd      # dynamic message-of-the-day login prompt indicating hostname
    - geerlingguy.repo-epel
    - influxdata.chrony         # sync time
    # - hxr.monitor-email
    - usegalaxy-eu.autoupdates  # keep all of our packages up to date
    - usegalaxy-eu.autofs
    # - ssh-host-sign
    - usegalaxy-eu.ansible-htcondor-grycap
    # - dj-wasabi.telegraf
    - ssh_hardening        
