---
- name: UseGalaxy.eu
  hosts: usegalaxy_it_01
  become: true
  become_user: root
  vars:
    galaxy_config_file: /opt/galaxy/config/galaxy.ini
    galaxy_root: /opt/galaxy
  vars_files:
    - group_vars/gxconfig.yml          # The base galaxy configuration
    - secret_group_vars/db-main.yml    # DB URL + some postgres stuff
    - secret_group_vars/all.yml        # All of the other assorted secrets...
  tasks:
    - name: Create Galaxy DB
      command: "{{ galaxy_root }}/venv/bin/python {{ galaxy_root }}/server/scripts/create_db.py -c {{ galaxy_config_file }}"
      args:
        chdir: "{{ galaxy_root }}/server/"
    
    - name: Create Galaxy install DB
      command: "{{ galaxy_root}}/venv/bin/python {{ galaxy_root }}/server/scripts/create_db.py -c {{ galaxy_config_file }} install"
      args:
        chdir: '{{ galaxy_root }}/server/'
    
    - name: Update Galaxy DB
      command: "{{ galaxy_root}}/venv/bin/python {{ galaxy_root }}/server/scripts/manage_db.py -c {{ galaxy_config_file }} upgrade install"
      args:
        chdir: '{{ galaxy_root}}/server/'
