preferences:
  webhook_overlay_search:
    description: Configuration option for your search results
    inputs:
      - name: max_search_results
        label: Maximum number of search results
        type: text
        required: False

  use_cached_job:
    description: Do you want to be able to re-use previously run jobs ?
    inputs:
      - name: use_cached_job_checkbox
        label: Do you want to be able to re-use  equivalent jobs ?
        type: boolean
        checked: false
        value: false
        help: If you select yes, you will be able to select for each tool and workflow run if you would like to use this feature.

  localization:
    description: Localization
    inputs:
      - name: locale
        label: Prefered language
        type: select
        required: False
        options:
          - [Navigator default, auto]
          - [中文, zh]
          - [English, en]
          - [Español, es]
          - [Français, fr]
          - [日本語, ja]

  distributed_compute:
    description: Use distributed compute resources
    inputs:
      - name: remote_resources
        label: Remote resources id
        type: select
        required: False
        options:
          - ["Select the remote resources", None]
          - ["default - Galaxy will decide where to put your job", None]
          # - ["Freiburg (Germany) - Condor cluster using Singularity with Conda", condor_singularity_with_conda]
          # - ["Joint remote GPU cluster using docker engine - Galaxy will decide where to put your job", remote_condor_cluster_gpu_docker]
          # - ["Joint remote CPU cluster using singularity engine - Galaxy will decide where to put your job", remote_condor_cluster_singularity]
          - ["Freiburg (Germany) - Mira's test Pulsar", mira-pulsar]
          - ["Freiburg (Germany) - Sanjay's test Pulsar", sanjay-pulsar]
          # - ["Freiburg (Germany) - de.NBI cloud - docker", remote_cluster_mq_docker_de01]
          #- ["Freiburg (Germany) - de.NBI cloud - singularity, 2wd true", remote_cluster_mq_singularity_2wdtrue_de01]
          # - ["Tübingen (Germany) - de.NBI cloud", remote_cluster_mq_de02]
          # - ["Freiburg (Germany) - de.NBI cloud GPU", remote_cluster_mq_de03]
          # - ["Freiburg (Germany) - de.NBI cloud GPU - docker", remote_cluster_mq_docker_de03]
          - ["Rennes (France) - GenOuest bioinformatics", fr-pulsar]
          - ["Bari (Italy) - RECAS", it-pulsar]
          - ["Cineca (Italy) - CINECA", it02-pulsar]
          - ["Bari (Italy) - RECAS 5", it05-pulsar]
          - ["Palermo (Italy) - GARR", it03-pulsar]
          # - ["Palermo (Italy) - GARR, 2wd true", remote_cluster_mq_2wdtrue_it03]
          # - ["Palermo (Italy) - GARR, 2wd falsef", remote_cluster_mq_2wdfalse_it03]
          # - ["Lisbon (Portugal) - Tecnico ULisboa", remote_cluster_mq_pt01]
          # - ["Oxfordshire (UK) - Diamond Light Source", remote_cluster_mq_uk01]
          # - ["Oxfordshire (UK) - Diamond Light Source - GPUs on docker", remote_cluster_mq_docker_uk01]
          - ["Brussel (Belgium) - VIB", be-pulsar]
          # - ["Bergen (Norway) - UIB", no-pulsar]
          - ["Prague (Czech Republic) - MetaCentrum", cz-pulsar]
          - ["Bratislava (Slovakia)", sk-pulsar]

  ega_account:
    description: Your EGA (European Genome Archive) account
    inputs:
      - name: username
        label: Username
        type: text
        required: False
      - name: password
        label: Password
        type: password
        required: False

  dropbox:
    description: Your Dropbox account
    inputs:
      - name: access_token
        label: Dropbox access token
        type: password
        required: False

  # Used in file_sources_conf.yml
  nextcloud:
    description: Your Personal Nextcloud / ownCloud account
    inputs:
      - name: url
        label: Server Domain (e.g. https://myowncloud.org)
        type: text
        required: False
      - name: root
        label: Server Path (should end with /remote.php/webdav, e.g. /a/sub/path/remote.php/webdav)
        type: text
        required: False
      - name: username
        label: Username
        type: text
        required: False
      - name: password
        label: Password
        type: password
        required: False

  omero_account:
    description: Your OMERO instance connection details
    inputs:
      - name: username
        label: Username
        type: text
        required: False
      - name: password
        label: Password
        type: password
        required: False

  ena_webin_account:
    description: Your ENA Webin account details
    inputs:
      - name: webin_id
        label: ENA Webin ID
        type: text
        required: False
      - name: password
        label: Password
        type: password
        required: False

  c3s_account:
    description: Your CDS API Key (Copernicus Climate Change Service API Key)
    inputs:
      - name: c3s_cds_apikey
        label: C3S CDS API Key
        type: password
        required: False

  cads_account:
    description: Your Copernicus ADS API Key (Copernicus Atmosphere Data Store API Key)
    inputs:
      - name: cads_apikey
        label: Copernicus ADS API Key
        type: password
        required: False

  gitlabfs:
    description: Your DataPLANT ARC Gitlab access details https://git.nfdi4plants.org
    inputs:
      - name: read_access_token
        label: API Read Access Token
        type: password
        required: True
