---
# This is a file of variables that will be processed in job_conf.yml.j2
# This is needed, because it contains other variables

galaxy_jobconf:
  plugin_workers: 8
  handlers:
    count: "{{ galaxy_systemd_handlers }}"
    assign_with: db-skip-locked
    max_grab: 16
    ready_window_size: 32
  plugins:
    #- id: drmaa
    #load: galaxy.jobs.runners.drmaa:DRMAAJobRunner
    #workers: 3
    - id: condor
      load: galaxy.jobs.runners.condor:CondorJobRunner
    - id: local
      load: galaxy.jobs.runners.local:LocalJobRunner
    - id: pulsar_embedded
      load: galaxy.jobs.runners.pulsar:PulsarEmbeddedJobRunner
      pulsar_config: "{{ galaxy_config_dir }}/pulsar_app.yml"
  pulsar_it03:
    load: galaxy.jobs.runners.pulsar:PulsarMQJobRunner
    amqp_ack_republish_time: 300
    amqp_acknowledge: true
    amqp_consumer_timeout: 2.0
    amqp_publish_retry: true
    amqp_publish_retry_max_retries: 60
    amqp_url: pyamqp://pulsar_it03:{{ rabbitmq_password_pulsar_it03 }}@rabbitmq-usegalaxy-it.cloud.ba.infn.it:5671//pulsar/pulsar_it03?ssl=1
    galaxy_url: https://usegalaxy-it.cloud.ba.infn.it
    manager: production
  pulsar_it05:
    load: galaxy.jobs.runners.pulsar:PulsarMQJobRunner
    amqp_ack_republish_time: 300
    amqp_acknowledge: true
    amqp_consumer_timeout: 2.0
    amqp_publish_retry: true
    amqp_publish_retry_max_retries: 60
    amqp_url: pyamqp://pulsar_it05:{{ rabbitmq_password_pulsar_it05 }}@rabbitmq-usegalaxy-it.cloud.ba.infn.it:5671//pulsar/pulsar_it05?ssl=1
    galaxy_url: https://usegalaxy-it.cloud.ba.infn.it
    manager: production
